### ISSUE TITLE
No history button in "code view" beta

### ISSUE THREAD

**Issue by texastoland** [LuisReinoso/git-history-browser-extension#12]
New ["code view"](https://github.blog/changelog/2022-11-09-introducing-an-all-new-code-search-and-code-browsing-experience/#the-all-new-code-browsing-experience) has a different HTML structure.

**Comment by ahmetb** [comment]
@texastoland Do you have the wrong link in your issue description? I also see the same issue. No `Open in Git History` button anymore.

<img width="1209" alt="image" src="https://github.com/LuisReinoso/git-history-browser-extension/assets/159209/0c839191-3272-4b6e-888f-e99255b68cf4">

**Comment by texastoland** [comment]
Link fixed thanks 🙊 I suspect the change in HTML structure broke the injection point for several extensions. The [VS Code extension](https://marketplace.visualstudio.com/items?itemName=pomber.git-file-history) works great though!

**Comment by LuisReinoso** [comment]
Hi Guys, I really didn't notice this bug. I will fix it right now. Thanks a lot for notice it
