### ISSUE TITLE
Manifest V3 support

### ISSUE THREAD

**Issue by rakleed** [LuisReinoso/git-history-browser-extension#16]
The ability to install Manifest V2 extensions [will be completely unavailable in the coming months](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline). Please update your extension to [Manifest V3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3).

**Comment by LuisReinoso** [comment]
Thanks for the remainder :+1: I will do it soon.
