### ISSUE TITLE
first enter file ,it doesn`t work.

### ISSUE THREAD

**Issue by lisinaner** [LuisReinoso/git-history-browser-extension#2]
in chrome,first enter a file,script doesn't work.need to refresh ,then can see the button.
l test it in tampermonkey ,the same result is happen.
maybe in github ,first enter file, all script doesn't work ,to make website fast.
can this be resolve?

**Comment by LuisReinoso** [comment]
Hi @lisinaner. I'm going to make some experiments until know how to see the button on first view. I didn't see this before publish this extension.

Thanks for install this extension and open this issue.

**Comment by LuisReinoso** [comment]
I have solved this issue. Executing this script after js, css, and each time you visit github.

**Comment by lisinaner** [comment]
Thank you,you can publish it in chrome.

**Comment by LuisReinoso** [comment]
Yes, I have published on chrome and firefox maybe 1 hour ago.
Please tell me if all is ok.

**Comment by lisinaner** [comment]
yes,all is ok.
