### ISSUE TITLE
github enterprise support: change github url

### ISSUE THREAD

**Issue by BK-Choi** [LuisReinoso/git-history-browser-extension#3]
It would be great if you have any plan to support custom github url.
I want to use this extension at work. 🙏 
Thank you.

**Comment by LuisReinoso** [comment]
Hi! @BK-Choi Could you tell me more information about github enterprise.
Is the same github UI?
Just change url? Example.
`https://github.com/LuisReinoso/git-history-browser-extension/blob/master/extension/main.js `
become
`https://custom.domine/LuisReinoso/git-history-browser-extension/blob/master/extension/main.js `

**Comment by Billy-** [comment]
@LuisReinoso yes, everything is the same except the domain, which would be `<your-org>.github.com`

**Comment by BK-Choi** [comment]
@LuisReinoso
As @Billy- said, we are using exactly same github UI with different URL.
But, this case is `https://<custom-url>.com`

I tried like below, but doesn't work
- query : `https://<custom-url>.com/{organization}/{project}/git-history-browser-extension/blog/master/<file>`
- result : `Not Found`
  - http status code : 404

**Comment by LuisReinoso** [comment]
Ok I understand only change `<your-org>.github.com` like @Billy- said.
I need some help to test that is working before to publish on stores. I'm going to write instructions about how to use it in development on README.md.

**Comment by LuisReinoso** [comment]
I have analyzed better and I have two more thing to say before to change this extension.

1. Did you try open your project into https://githistory.xyz/ ? Remember that this extension add a button to redirect to this page.
2. Reading source code of git history https://github.com/pomber/git-history/blob/master/src/git-providers/github-commit-fetcher.js You could see that for fetch github commit use github API but I don't think that is the same of github enterprise. Maybe git history not support for github enterprise.
3. Remember that git history has a [cli](https://github.com/pomber/git-history/tree/master/cli) and [vs code extension](https://marketplace.visualstudio.com/items?itemName=pomber.git-file-history) that could help to see file history.

**Comment by BK-Choi** [comment]
found possible issue.
Github Enterprise API v3 URL is not `https://api.{custom-domain}`, and is `https://{custom-domain}/api/v3`
therefore, this issue has two points to discuss.

1. support custom URL for Github Enterprise
2. suport Github Enterprise API v3

What do you think?

- - -
1. As you might know, Github Enterprise is on-premise, open with `https://githistory.xyz/~` leads me to index page of githistory.xyz
2. Here's Github Enterprise API doc. I hope this helps.
  - https://developer.github.com/enterprise/2.14/v3/
3. OK. I will try them.

**Comment by LuisReinoso** [comment]
**Summary**
- Git history don't support Github Enterprise API v3 and custom URL for Github Enterprise
- I think that is necessary to **open an issue on [git-history](https://github.com/pomber/git-history/issues) repo** to talk about this requirement.
- Make a pull request to add another git provider to support Github Enterprise API v3 . I think that **authentication it's a problem**
- This extension would support Github Enterprise if git-history support it.

**Ideas**
- **On old version of git history**: I have found a interesting [pull request](https://github.com/pomber/git-history/pull/39) on git history and this [link](https://gitpod.io/#snapshot/00eb3260-8b6d-4f3e-b7b6-29fc7a6208e1) contain old version of git history but I think that is easy to change api request and implement authentication.
   - If developer environment not start try `yarn`
   - `yarn start` and select another port.
   - make [authentication](https://developer.github.com/enterprise/2.14/v3/#authentication) to make valid request 
   - change API request in `github.js` file to Github Enterprise API v3 equivalent. 
   - if all is ok open (just an example - url is from gitpod.io)
`https://3000-esadsa-5465-545f-815csa-sadsa56.ws-us0.gitpod.io/:username/:repo/blob/master/:file`
   - **maybe the best option is to make this steps on your local machine and deploy on your own server and change this extension to redirect you to new server**
- **On actual version of git history**: check [this issue](https://github.com/pomber/git-history/issues/66#issuecomment-462072296) to deploy your own version. Before make **[authentication](https://developer.github.com/enterprise/2.14/v3/#authentication)** and change API request then modify this extension to add your own button to your Github Enterprise.

**Comment by BK-Choi** [comment]
You're 1000% right. This issue should've opened on git-history repo.
Thank you for your quick&detailed response.
