### ISSUE TITLE
A new Open in Git History button is being created each time I click on a line gutter

### ISSUE THREAD

**Issue by marcofugaro** [LuisReinoso/git-history-browser-extension#4]
Steps to reproduce:

1. Open a file in github

2. Click on the line gutter to highlight a line, if you want you can do it multiple times

![image](https://user-images.githubusercontent.com/7217420/54913563-50bb9180-4ef3-11e9-9c2f-b314dfdf444d.png)

3. Soon you'll have this

![image](https://user-images.githubusercontent.com/7217420/54913654-7ea0d600-4ef3-11e9-8ae1-41c758d5e56f.png)

i think it's related to the url changing?

**Comment by LuisReinoso** [comment]
Hi, today I'm going to release a new version that include a pull request that solve this issue.
Thanks to open this issue.
