### ISSUE TITLE
Extension prevents login to bitbucket.org

### ISSUE THREAD

**Issue by jaraco** [LuisReinoso/git-history-browser-extension#7]
Today I found myself unable to log into bitbucket.org. When I browse to https://bitbucket.org and click on the 'Log In' link, I get a blank page. The 'onload' event fails to trigger the form submission, so the login process hangs on a blank page. Disabling this extension, the process proceeds as expected.

I love this extension. I hope this issue can be fixed.

**Comment by LuisReinoso** [comment]
Hi @jaraco. I had test it. 
- Chrome v72: Not problem 
- **Firefox v63: Issue is found.**
Could you tell me witch browser did you use when you found this issue?

Thanks to open this issue.

**Comment by jaraco** [comment]
Apologies - I didn't realize the extension also ran on Chrome. I encountered the issue on Firefox 66, consistent with your finding.

**Comment by LuisReinoso** [comment]
I have try again and doesn't have any problem on login tested on `browser extension version: 1.0.4.`
On the other hand, I have notice that bitbucket has obfuscate its UI I have made some updates to enable add git history button on bitbucket interface. Try new version: 1.0.5.

PD: @jaraco Sorry for late update response. This last two months were so busy and I had sick.
Thanks.
